// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using HOApp_2017.ScoutsEnGidsen.HO.BL.VO;
using TableView.Cell;
using UIKit;

namespace HOApp_2017.iOS
{
	public partial class ProgrammSingleCell : BaseTableViewCell
	{
		public ProgrammSingleCell (IntPtr handle) : base (handle)
		{
		}

		public static readonly NSString Key = new NSString("ProgrammSingleCell");
		public override void SetData(object data)
		{
			lblSubTitle.Text = (data as ProgramItemVO).Title;
            if ((data as ProgramItemVO).Location != null)
                lblTitle.Text = (data as ProgramItemVO).Location.Name;
            else
                lblTitle.Text = string.Empty;
            lblTimeFrame.Text = (data as ProgramItemVO).StartTime + (((data as ProgramItemVO).StartTime != null & (data as ProgramItemVO).EndTime != null) ? " - " : "") + (data as ProgramItemVO).EndTime;
		}

		protected override void Initialize()
		{
			Console.WriteLine("initialize");

            lblTimeFrame.Font = UIFont.FromName("Roboto-Regular", 14);
            lblTitle.Font = UIFont.FromName("Roboto-Italic", 14);
            lblSubTitle.Font = UIFont.FromName("Roboto-Bold", 16);
		}
    }
}
