// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using TableView.Cell;
using UIKit;

namespace HOApp_2017.iOS
{
	public partial class SideMenuFooter : BaseTableViewCell
	{
		public SideMenuFooter (IntPtr handle) : base (handle)
		{
		}
		public static readonly NSString Key = new NSString("SideMenuFooter");
		public override void SetData(object data)
		{
			throw new NotImplementedException();
		}

		protected override void Initialize()
		{
			btnFB.SetImage(UIImage.FromBundle("SharedAssets/Images/Menu/facebook.png"), UIControlState.Normal);

			btnInsta.SetImage(UIImage.FromBundle("SharedAssets/Images/Menu/instagram.png"), UIControlState.Normal);

			btnTwitter.SetImage(UIImage.FromBundle("SharedAssets/Images/Menu/twitter.png"), UIControlState.Normal);
		}
	}
}
