// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using HOApp_2017.iOS.SG.ViewControllers.Base;
using HOApp_2017.ScoutsEnGidsen.HO.BL.Controllers;
using SidebarNavigation;
using UIKit;

namespace HOApp_2017.iOS
{
	public partial class ContentViewController : BaseViewController
	{
		
		#region delegates

		#endregion

		#region variables

		#endregion

		#region constructor
		public ContentViewController(IntPtr handle) : base(handle)
		{
		}

		#endregion

		#region properties

		#endregion

		#region public methods

		#region override methods

		#region Viewcycle
		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			btnOpenMenu.TouchUpInside+= BtnOpenMenu_TouchUpInside;
			AppController.Instance.NavigationController.GoToPageEvent+= GoToPageHandler;
		}
		#endregion

		#endregion

		#endregion

		#region private methods
		void BtnOpenMenu_TouchUpInside(object sender, EventArgs e)
		{
			SidebarController.ToggleMenu();
		}


		void GoToPageHandler(ScoutsEnGidsen.HO.BL.Controllers.NavigationController.PagesEnum page, ScoutsEnGidsen.HO.BL.Controllers.BaseContentController controller)
		{
			Console.WriteLine("Should go to page " + page.ToString());
		}
		#endregion


	}
}
