// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using HOApp_2017.iOS.SG.ViewControllers.Base;
using HOApp_2017.ScoutsEnGidsen.HO.BL.Controllers;
using UIKit;

namespace HOApp_2017.iOS
{
	public partial class InfoViewController : BaseContentViewController
	{
		public InfoViewController (IntPtr handle) : base (handle)
		{
		}

        public override void SetData()
        {
            base.SetData();
        }

        public override void ViewDidLoad()
        {
            lblTitle.Font = UIFont.FromName("Roboto-Bold", 21);
            lblSubtitleInfoPoint.Font = UIFont.FromName("Roboto-Italic", 18);
            lblDetailInfoPoint.Font = UIFont.FromName("Roboto-Regular", 15);
            lblSubtitleBar.Font = UIFont.FromName("Roboto-Italic", 18);
            lblDetailBar.Font = UIFont.FromName("Roboto-Regular", 15);
            lblSubtitleWIFI.Font = UIFont.FromName("Roboto-Italic", 18);
            lblDetailWIFI.Font = UIFont.FromName("Roboto-Regular", 15);
            lblSubtitleFirstAid.Font = UIFont.FromName("Roboto-Italic", 18);
            lblDetailFirstAid.Font = UIFont.FromName("Roboto-Regular", 15);

            lblCallEmergency.Font = UIFont.FromName("Roboto-Italic", 12);
            lblShowFirstAid.Font = UIFont.FromName("Roboto-Italic", 12);

			btnShowFirstAid.Layer.CornerRadius = 5;
            btnCallEmergency.Layer.CornerRadius = 5;

            btnShowFirstAid.TouchUpInside+= BtnShowFirstAid_TouchUpInside;
            btnCallEmergency.TouchUpInside+= BtnCallEmergency_TouchUpInside;
        }

        void BtnShowFirstAid_TouchUpInside(object sender, EventArgs e)
        {
            (Controller as InfoPageController).ShowFirstAidLocation();
        }

        void BtnCallEmergency_TouchUpInside(object sender, EventArgs e)
        {
            var url = new NSUrl("tel:+32474261401");
            UIApplication.SharedApplication.OpenUrl(url);
        }
    }
}
