// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using HOApp_2017.iOS.SG.ViewControllers.Base;
using HOApp_2017.ScoutsEnGidsen.HO.BL.Controllers;
using UIKit;

namespace HOApp_2017.iOS
{
	public partial class IntroViewController : BaseContentViewController
	{
        IntroPageController _controller;
		public IntroViewController (IntPtr handle) : base (handle)
		{
		}

        public override void SetData()
        {
            //throw new NotImplementedException();
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            _controller = Controller as IntroPageController;
            lblIntroText.Font = UIFont.FromName("Roboto-Italic", 17);
            lblIntroTitle.Font = UIFont.FromName("Roboto-Bold", 21);
            lblIntroSubTitle.Font = UIFont.FromName("Roboto-Regular", 12);
            lblIntroTitle.Text = _controller.Title;
            lblIntroSubTitle.Text = _controller.SubTitle;
            lblIntroText.Text = _controller.IntroText;
            imgIntroTopImage.Image = UIImage.FromBundle("SharedAssets/Images/intro/anton.jpg");
        }
	}
}
