// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using HOApp_2017.iOS.SG.ViewControllers.Base;
using UIKit;

namespace HOApp_2017.iOS
{
	public partial class IntroViewController : BaseContentViewController
	{
		public IntroViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
