// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using HOApp_2017.iOS.SG.ViewControllers.Base;
using HOApp_2017.ScoutsEnGidsen.HO.BL.Controllers;
using UIKit;

namespace HOApp_2017.iOS
{
	public partial class SideMenuViewController : BaseViewController
	{
		public SideMenuViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			btnIntro.Tag = (int)ScoutsEnGidsen.HO.BL.Controllers.NavigationController.PagesEnum.INTRO;
			btnProgramm.Tag = (int)ScoutsEnGidsen.HO.BL.Controllers.NavigationController.PagesEnum.PROGRAM;
			btnIntro.TouchUpInside+= BtnIntro_TouchUpInside;
			btnProgramm.TouchUpInside += BtnIntro_TouchUpInside;
		}

		void BtnIntro_TouchUpInside(object sender, EventArgs e)
		{
			SidebarController.CloseMenu();
			UIButton b = sender as UIButton;
			AppController.Instance.NavigationController.SideMenuButtonClicked((NavigationController.PagesEnum)(int)b.Tag);
		}
	}
}
