// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using HOApp_2017.iOS.SG.ViewControllers.Base;
using HOApp_2017.ScoutsEnGidsen.HO.BL.Controllers;
using UIKit;

namespace HOApp_2017.iOS
{
	public partial class SongViewController : BaseContentViewController
	{
        SongPageController _controller;
		public SongViewController (IntPtr handle) : base (handle)
		{
		}

		public override void SetData()
		{
			//throw new NotImplementedException();
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			_controller = Controller as SongPageController;
            lblSongText.Font = UIFont.FromName("Roboto-Italic", 17);
            lblTitle.Font = UIFont.FromName("Roboto-Bold", 21);
            lblSubtitle.Font = UIFont.FromName("Roboto-Regular", 12);
            lblTitle.Text = _controller.Title;
            lblSubtitle.Text = _controller.SubTitle;
            lblSongText.Text = _controller.SongText;
            imgYearBadge.Image = UIImage.FromBundle("SharedAssets/Images/Jaarthema/jaarthema.jpg");
		}
	}
}
