// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using HOApp_2017.ScoutsEnGidsen.HO.BL.VO;
using TableView.Cell;
using UIKit;

namespace HOApp_2017.iOS
{
	public partial class ProgramMultiCell : BaseTableViewCell
	{
		public ProgramMultiCell (IntPtr handle) : base (handle)
		{
		}
		public static readonly NSString Key = new NSString("ProgramMultiCell");
		public override void SetData(object data)
		{
			lblTitle.Text = (data as ProgramItemVO).Title;
			
			lblTimeFrame.Text = (data as ProgramItemVO).StartTime + (((data as ProgramItemVO).StartTime != null & (data as ProgramItemVO).EndTime != null) ? " - " : "") + (data as ProgramItemVO).EndTime;

		}

		protected override void Initialize()
		{
			Console.WriteLine("initialize");
		}
	}
}
