// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using HOApp_2017.ScoutsEnGidsen.HO.BL.VO;
using TableView.Cell;

namespace HOApp_2017.iOS
{
	public partial class SideMenuTableViewCell : BaseTableViewCell
	{
		public SideMenuTableViewCell(IntPtr handle) : base(handle)
		{

		}
		public static readonly NSString Key = new NSString("SideMenuTableViewCell");
		public override void SetData(object data)
		{
			Console.WriteLine(data);
			lblMenuItemTitle.Text = (data as MenuItemVO).MenuItemText;
		}

		protected override void Initialize()
		{
			Console.WriteLine("initialize");
		}
	}
}
