// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using TableView.Cell;
using UIKit;

namespace HOApp_2017.iOS
{
	public partial class SideMenuFooterLogo : BaseTableViewCell
	{
		public SideMenuFooterLogo (IntPtr handle) : base (handle)
		{
		}
        public static readonly NSString Key = new NSString("SideMenuFooterLogo");
        public override void SetData(object data)
        {
            //throw new NotImplementedException();
        }

        protected override void Initialize()
        {
            imgLogo.Image = UIImage.FromBundle("SharedAssets/Images/Menu/hologo.png");
        }
    }
}
