// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using HOApp_2017.iOS.SG.TableView.Source;
using HOApp_2017.iOS.SG.ViewControllers.Base;
using HOApp_2017.ScoutsEnGidsen.HO.BL.Controllers;
using HOApp_2017.ScoutsEnGidsen.HO.BL.VO;
using UIKit;

namespace HOApp_2017.iOS
{
	public partial class ProgramViewController : BaseContentViewController
	{
		public ProgramViewController (IntPtr handle) : base (handle)
		{
		}

        public override void SetData()
        {
            tblProgram.Source = new ProgramTableViewSource(Controller as ProgramPageController);
			(Controller as ProgramPageController).ProgramLoadedEvent += Controller_ProgramLoadedEvent;
			(Controller as ProgramPageController).LoadData();
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            SetData();
        }

		void Controller_ProgramLoadedEvent(List<ProgramItemVO> ProgramItems)
		{
            InvokeOnMainThread(() =>
            {
				(tblProgram.Source as ProgramTableViewSource).ProgramDays = ProgramItems;
				tblProgram.ReloadData();
            });
           
		}
    }
}
