// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using HOApp_2017.iOS.SG.ViewControllers.Base;
using HOApp_2017.ScoutsEnGidsen.HO.BL.Controllers;
using UIKit;

namespace HOApp_2017.iOS
{
	public partial class RulesViewController : BaseContentViewController
	{
        RulesPageController _controller;
		public RulesViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            _controller = Controller as RulesPageController;
            lblIntro.Font = UIFont.FromName("Roboto-Italic", 17);
			lblTitle.Font = UIFont.FromName("Roboto-Bold", 21);
            lblRulesFooter.Font = UIFont.FromName("Roboto-Italic", 17);

			lblTitle.Text = _controller.Title;
            lblRulesFooter.Text = _controller.FooterText;
			lblIntro.Text = _controller.IntroText;

			imgRule1.Image = UIImage.FromBundle("SharedAssets/Images/Rules/alcohol.jpg");
            imgRule2.Image = UIImage.FromBundle("SharedAssets/Images/Rules/eigendrank.jpg");
            imgRule3.Image = UIImage.FromBundle("SharedAssets/Images/Rules/nachtrust.jpg");
            imgRule4.Image = UIImage.FromBundle("SharedAssets/Images/Rules/respect.jpg");
            imgRule5.Image = UIImage.FromBundle("SharedAssets/Images/Rules/actie.jpg");
            imgRule6.Image = UIImage.FromBundle("SharedAssets/Images/Rules/geendrugs.jpg");
            imgRule7.Image = UIImage.FromBundle("SharedAssets/Images/Rules/rookzones.jpg");

        }
	}
}
