// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Linq;
using Foundation;
using HOApp_2017.iOS.SG.TableView.Source;
using HOApp_2017.iOS.SG.ViewControllers.Base;
using HOApp_2017.ScoutsEnGidsen.HO.BL.Controllers;
using HOApp_2017.ScoutsEnGidsen.HO.BL.VO;
using UIKit;

namespace HOApp_2017.iOS
{
	public partial class SideMenuViewController : BaseViewController
	{
		public SideMenuViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			tblSideMenu.Source = new SideMenuTableViewSource() { Items = AppController.Instance.NavigationController.MenuItems.ToList() };
            btnMenuTitle.TouchUpInside+= BtnMenuTitle_TouchUpInside;
		}


        void BtnMenuTitle_TouchUpInside(object sender, EventArgs e)
        {
            AppController.Instance.NavigationController.SideMenuButtonClicked(ScoutsEnGidsen.HO.BL.Controllers.NavigationController.PagesEnum.INTRO);
        }
    }
}
