# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HO gids' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HO gids
pod 'AppCenter'
pod 'Firebase/Core'
pod 'Kingfisher', '~> 4.0'
pod 'SQLite.swift'
end
